/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package Pane;

import java.awt.Component;
import java.util.Calendar;
import java.util.Date;

/**
 *
 * @author Willas Tobing
 */
public class CalendarDate extends javax.swing.JLayeredPane {

    /**
     * Creates new form Calendar
     */
    private int month;
    private int year;

    public CalendarDate(int month, int year) {
        initComponents();
        this.month = month;
        this.year = year;
        init();
    }

    private void init() {
        mon.asTitle();
        tue.asTitle();
        wed.asTitle();
        thu.asTitle();
        fri.asTitle();
        sat.asTitle();
        sun.asTitle();
        setDate();
    }
 
   private void setDate() {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.YEAR, year);
        calendar.set(Calendar.MONTH, month - 1); // month january as 0 thats why start from 0
        calendar.set(Calendar.DATE, 1);
        int startDay = calendar.get(Calendar.DAY_OF_WEEK) - 1; // get day of week -1 to index
        calendar.add(Calendar.DATE, -startDay);
        ToDay toDay = getToDay();
        for ( Component com : getComponents()){
            Cell cell = (Cell) com;
            if (!cell.isTitle()) {
                cell.setText(calendar.get(Calendar.DATE) + "");
                cell.setDate(calendar.getTime());
                cell.currentMonth(calendar.get(Calendar.MONTH) == month - 1);
                if (toDay.isToDay(new ToDay(calendar.get(Calendar.DATE), calendar.get(Calendar.MONTH) + 1, calendar.get(Calendar.YEAR)))) {
                    cell.setAsToDay();
                }
                calendar.add(Calendar.DATE, 1); // up 1 day
            }
        }
    }
   
   private ToDay getToDay(){
       Calendar calendar = Calendar.getInstance();
       calendar.setTime(new Date());
       return new ToDay(calendar.get(Calendar.DATE), calendar.get(Calendar.MONTH) + 1, calendar.get(Calendar.YEAR));
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sun = new Pane.Cell();
        mon = new Pane.Cell();
        tue = new Pane.Cell();
        wed = new Pane.Cell();
        thu = new Pane.Cell();
        fri = new Pane.Cell();
        sat = new Pane.Cell();
        cell9 = new Pane.Cell();
        cell10 = new Pane.Cell();
        cell12 = new Pane.Cell();
        cell13 = new Pane.Cell();
        cell14 = new Pane.Cell();
        cell15 = new Pane.Cell();
        cell16 = new Pane.Cell();
        cell17 = new Pane.Cell();
        cell11 = new Pane.Cell();
        cell18 = new Pane.Cell();
        cell19 = new Pane.Cell();
        cell20 = new Pane.Cell();
        cell21 = new Pane.Cell();
        cell22 = new Pane.Cell();
        cell23 = new Pane.Cell();
        cell24 = new Pane.Cell();
        cell25 = new Pane.Cell();
        cell26 = new Pane.Cell();
        cell27 = new Pane.Cell();
        cell28 = new Pane.Cell();
        cell29 = new Pane.Cell();
        cell30 = new Pane.Cell();
        cell31 = new Pane.Cell();
        cell32 = new Pane.Cell();
        cell33 = new Pane.Cell();
        cell34 = new Pane.Cell();
        cell35 = new Pane.Cell();
        cell36 = new Pane.Cell();
        cell37 = new Pane.Cell();
        cell38 = new Pane.Cell();
        cell39 = new Pane.Cell();
        cell40 = new Pane.Cell();
        cell49 = new Pane.Cell();
        cell41 = new Pane.Cell();
        cell42 = new Pane.Cell();
        cell43 = new Pane.Cell();
        cell44 = new Pane.Cell();
        cell45 = new Pane.Cell();
        cell46 = new Pane.Cell();
        cell47 = new Pane.Cell();
        cell8 = new Pane.Cell();
        cell48 = new Pane.Cell();

        setLayout(new java.awt.GridLayout(7, 7));

        sun.setForeground(new java.awt.Color(255, 51, 51));
        sun.setText("SUN");
        sun.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        sun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sunActionPerformed(evt);
            }
        });
        add(sun);

        mon.setText("MON");
        mon.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(mon);

        tue.setText("TUE");
        tue.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(tue);

        wed.setText("WED");
        wed.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(wed);

        thu.setText("THU");
        thu.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(thu);

        fri.setText("FRI");
        fri.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(fri);

        sat.setText("SAT");
        sat.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(sat);

        cell9.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell9);

        cell10.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell10);

        cell12.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell12);

        cell13.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell13);

        cell14.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell14);

        cell15.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell15);

        cell16.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell16);

        cell17.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell17);

        cell11.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell11);

        cell18.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell18);

        cell19.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell19);

        cell20.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell20);

        cell21.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell21);

        cell22.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell22);

        cell23.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell23);

        cell24.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell24);

        cell25.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell25);

        cell26.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell26);

        cell27.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell27);

        cell28.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell28);

        cell29.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell29);

        cell30.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell30);

        cell31.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell31);

        cell32.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell32);

        cell33.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell33);

        cell34.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell34);

        cell35.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell35);

        cell36.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell36);

        cell37.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell37);

        cell38.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell38);

        cell39.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell39);

        cell40.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell40);

        cell49.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell49);

        cell41.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell41);

        cell42.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell42);

        cell43.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell43);

        cell44.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell44);

        cell45.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell45);

        cell46.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell46);

        cell47.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell47);

        cell8.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell8);

        cell48.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        add(cell48);
    }// </editor-fold>//GEN-END:initComponents

    private void sunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sunActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Pane.Cell cell10;
    private Pane.Cell cell11;
    private Pane.Cell cell12;
    private Pane.Cell cell13;
    private Pane.Cell cell14;
    private Pane.Cell cell15;
    private Pane.Cell cell16;
    private Pane.Cell cell17;
    private Pane.Cell cell18;
    private Pane.Cell cell19;
    private Pane.Cell cell20;
    private Pane.Cell cell21;
    private Pane.Cell cell22;
    private Pane.Cell cell23;
    private Pane.Cell cell24;
    private Pane.Cell cell25;
    private Pane.Cell cell26;
    private Pane.Cell cell27;
    private Pane.Cell cell28;
    private Pane.Cell cell29;
    private Pane.Cell cell30;
    private Pane.Cell cell31;
    private Pane.Cell cell32;
    private Pane.Cell cell33;
    private Pane.Cell cell34;
    private Pane.Cell cell35;
    private Pane.Cell cell36;
    private Pane.Cell cell37;
    private Pane.Cell cell38;
    private Pane.Cell cell39;
    private Pane.Cell cell40;
    private Pane.Cell cell41;
    private Pane.Cell cell42;
    private Pane.Cell cell43;
    private Pane.Cell cell44;
    private Pane.Cell cell45;
    private Pane.Cell cell46;
    private Pane.Cell cell47;
    private Pane.Cell cell48;
    private Pane.Cell cell49;
    private Pane.Cell cell8;
    private Pane.Cell cell9;
    private Pane.Cell fri;
    private Pane.Cell mon;
    private Pane.Cell sat;
    private Pane.Cell sun;
    private Pane.Cell thu;
    private Pane.Cell tue;
    private Pane.Cell wed;
    // End of variables declaration//GEN-END:variables
}
