/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pane;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JOptionPane;
import javax.swing.Timer;

/**
 *
 * @author Willas Tobing
 */
public class TimerTarget extends javax.swing.JFrame {

    /**
     * Creates new form Timer
     */
    int hour, min, sec, newhour, newmin, newsec;
    Timer timer;
    boolean flag = true;
    boolean ifStop = false;
    public TimerTarget() {
        initComponents();
        
        
    }
//        // Adding hours in combobox
//        for (int i = 0; i < 24; i++) {
//            if (i < 10) {
//                cboxHour.addItem("0" + i);
//            } else {
//                cboxHour.addItem(i);
//            }
//        }
//        // Adding minutes in combobox
//        for (int i = 0; i < 60; i++) {
//            if (i < 10) {
//                cboxMin.addItem("0" + i);
//            } else {
//                cboxMin.addItem(i);
//            }
//        }
//        // adding seconds in combobox
//        for (int i = 0; i < 60; i++) {
//            if (i < 10) {
//                cboxSec.addItem("0" + i);
//            } else {
//                cboxSec.addItem(i);
//            }
//        }
//    }

     Datas datas;
    public class Datas{
        
        private int hour, minute;
        public Datas(int jam, int menit){
            hour =jam;
            minute = menit;
        }
            
        public int getHour(){
            return hour;
        }
        
        public int getMinute(){
            return minute;
        }
        
    }
    
    public void passData(String name, String category, String date, int jam, int menit){
        String Jam;
        String Menit;
        if (jam ==0) {
            Jam = ("0"+jam);
        }else{
            Jam = (""+jam);   
        }
        
        if (menit<10) {
            Menit = ("0"+menit);
        }else{
            Menit = (""+menit);
        }
        lblMin.setText(Menit);
        lblHour.setText(Jam);
        sec = Integer.parseInt(lblSec.getText());
        min = Integer.parseInt(lblMin.getText());
        hour = Integer.parseInt(lblHour.getText());
        
        namaTarget.setText(name);
        tanggalTarget.setText(date);
    }
    
    
    
    
    public void returnToMainClass(){
        
        if (sec>20) {
            min+=1;
        }
        datas= new Datas(hour, min);
    }
    public Datas returnData(){
        return datas;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblSec = new javax.swing.JLabel();
        lblHour = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStop = new javax.swing.JButton();
        btnStart = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblMin = new javax.swing.JLabel();
        namaTarget = new javax.swing.JLabel();
        tanggalTarget = new javax.swing.JLabel();
        back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Timer");

        lblSec.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lblSec.setText("00");

        lblHour.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lblHour.setText("00");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel4.setText(":");

        btnStop.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnStop.setText("Stop");
        btnStop.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStopActionPerformed(evt);
            }
        });

        btnStart.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        btnStart.setText("Start");
        btnStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStartActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel5.setText(":");

        lblMin.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        lblMin.setText("00");

        namaTarget.setText("jLabel2");

        tanggalTarget.setText("jLabel2");

        back.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        back.setText("Back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(back)
                        .addGap(18, 18, 18)
                        .addComponent(btnStart)
                        .addGap(18, 18, 18)
                        .addComponent(btnStop)
                        .addGap(62, 62, 62))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblHour)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel5)
                                .addGap(30, 30, 30)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(namaTarget)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMin)
                                        .addGap(33, 33, 33)
                                        .addComponent(jLabel4)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblSec)))
                                .addGap(81, 81, 81))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(tanggalTarget)
                                .addGap(179, 179, 179)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(71, 71, 71)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaTarget)
                .addGap(7, 7, 7)
                .addComponent(tanggalTarget)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHour)
                    .addComponent(lblSec)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(lblMin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart)
                    .addComponent(btnStop)
                    .addComponent(back))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStartActionPerformed
        // TODO add your handling code here:
        timer = new Timer(1000, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {

                if (ifStop) {
                    hour = newhour;
                    min = newmin;
                    sec = newsec;
                    ifStop = false;
                }

                if (sec == 0) {
                    sec = 60;
                    min--;
                }
                if (min < 0 ) {
                    if (hour == 0) {
                        JOptionPane.showMessageDialog(rootPane, "Your Time is Up", "Stopped", 0);
                        min = 0;
                        sec = 0;
                        timer.stop();
                    } else {
                        hour--;
                        min = 59;
                        sec--;
                    }
                } else {
                    sec--;

            if (sec < 10) {
                lblSec.setText("0" + sec);
            } else {
                lblSec.setText(" " + sec);
            }

            if (min < 10) {
                lblMin.setText("0" + min);
            } else {
                lblMin.setText(" " + min);
            }
            
            if (hour < 10) {
                lblHour.setText("0" + hour);
            } else {
                lblHour.setText("" + hour);
            }
                }
            }
        });
        timer.start();
    }//GEN-LAST:event_btnStartActionPerformed

    private void btnStopActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStopActionPerformed
        // TODO add your handling code here:
        newhour = hour;
        newmin = min;
        newsec = sec;
        ifStop = false;
        timer.stop();
    }//GEN-LAST:event_btnStopActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        // TODO add your handling code here:
        returnToMainClass();
        dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
     
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Timer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TimerTarget().setVisible(true);
            }
            
            
        });
        
         
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnStart;
    private javax.swing.JButton btnStop;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblHour;
    private javax.swing.JLabel lblMin;
    private javax.swing.JLabel lblSec;
    private javax.swing.JLabel namaTarget;
    private javax.swing.JLabel tanggalTarget;
    // End of variables declaration//GEN-END:variables

}
